// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AbortWorkflow(arg1:string):Promise<void>;

export function ActivateProfile(arg1:string):Promise<main.Settings>;

export function AddProfile(arg1:string,arg2:string):Promise<main.Settings>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CheckTfcmdVersion():Promise<main.VersionMismatchInfo>;

export function DeactivateProfile():Promise<main.Settings>;

export function DeleteProfile(arg1:string):Promise<main.Settings>;

export function ExportChat(arg1:string,arg2:string):Promise<void>;

export function GenerateSummary(arg1:string):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GetVersion():Promise<string>;

export function Logout():Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<main.Message>;

export function SetTheme(arg1:string):Promise<void>;

export function UpdateAdvancedSettings(arg1:string,arg2:string,arg3:boolean):Promise<main.Settings>;

export function UpdateGridSettings(arg1:string,arg2:string):Promise<main.Settings>;

export function UpdateProfile(arg1:string,arg2:string,arg3:string):Promise<main.Settings>;
