// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortWorkflow(arg1) {
  return window['go']['main']['App']['AbortWorkflow'](arg1);
}

export function AcknowledgeDisclaimer() {
  return window['go']['main']['App']['AcknowledgeDisclaimer']();
}

export function ActivateProfile(arg1) {
  return window['go']['main']['App']['ActivateProfile'](arg1);
}

export function AddProfile(arg1, arg2) {
  return window['go']['main']['App']['AddProfile'](arg1, arg2);
}

export function ApproveToolExecution(arg1) {
  return window['go']['main']['App']['ApproveToolExecution'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckTfcmdVersion() {
  return window['go']['main']['App']['CheckTfcmdVersion']();
}

export function DeactivateProfile() {
  return window['go']['main']['App']['DeactivateProfile']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExportChat(arg1, arg2) {
  return window['go']['main']['App']['ExportChat'](arg1, arg2);
}

export function GenerateSummary(arg1) {
  return window['go']['main']['App']['GenerateSummary'](arg1);
}

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RejectToolExecution(arg1) {
  return window['go']['main']['App']['RejectToolExecution'](arg1);
}

export function RequestToolApproval(arg1) {
  return window['go']['main']['App']['RequestToolApproval'](arg1);
}

export function SaveSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetSafetyMode(arg1) {
  return window['go']['main']['App']['SetSafetyMode'](arg1);
}

export function SetSmartSafetyThreshold(arg1) {
  return window['go']['main']['App']['SetSmartSafetyThreshold'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ToggleToolOverride(arg1) {
  return window['go']['main']['App']['ToggleToolOverride'](arg1);
}

export function UpdateAdvancedSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateAdvancedSettings'](arg1, arg2, arg3, arg4);
}

export function UpdateGridSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateGridSettings'](arg1, arg2);
}

export function UpdateProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3);
}
